from .compiler import Compiler
from .config import OUTPUT
from .utils import save,banner,ok,timestamp
def run():
    banner()
    html=Compiler().compile()
    html=f"<!-- Generated by TLS Builder\nBuild: {timestamp()} -->\n"+html
    save(OUTPUT,html)
    ok("index.html generado")
